version: '3.8'

services:
  mongodb:
    image: mongo:${MONGO_VERSION:-4.4.6}
    container_name: mongodb
    ports:
      - ${MONGO_PORT:-27017}:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongodb:/data/db
    networks:
      - mongodb

volumes:
  mongodb:
    name: mongodb
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./mongo-data

networks:
  mongodb:
    name: mongo
    driver: bridge
