version: '3.8'

services:
  mongodb:
    image: mongo:${MONGO_VERSION:-4.4.6}
    container_name: mongodb
    ports:
      - ${MONGO_PORT:-27017}:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    networks:
      - mongodb_network
    restart: always

  mongo-express:
    image: mongo-express:${MONGO_EXPRESS_VERSION:-1.0.2-18}
    container_name: mongo-express
    restart: always
    ports:
      - ${MONGO_EXPRESS_PORT:-8001}:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_EXPRESS_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_EXPRESS_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_EXPRESS_USER}:${MONGO_EXPRESS_PASSWORD}@mongodb:${MONGO_PORT:-27017}/
      ME_CONFIG_BASICAUTH: false
    networks:
      - mongodb_network

volumes:
  mongodb_data:
    name: mongodb_data
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./mongo/data

networks:
  mongodb_network:
    name: mongodb_network
    driver: bridge
